version: '3'

networks: 
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-laravel
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
      - mysql
    networks: 
      - laravel
  

  mysql:
    image: mysql:5.7.22
    container_name: mysql-laravel
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - laravel

  app:
    build:
      args: 
        user: www
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks: 
      - laravel